cabal-version:      2.4
name:               math-parser
version:            0.1.0
synopsis:           Fourteen math-expression evaluation strategies, idiomatic Haskell
build-type:         Simple

common warnings
    ghc-options: -Wall -O2

library
    import:           warnings
    hs-source-dirs:   src
    exposed-modules:  MathParser.Lexer
                      MathParser.Strategies
    build-depends:    base >=4 && <5
                    , array
                    , containers
    default-language: Haskell2010

executable bench
    import:           warnings
    hs-source-dirs:   app
    main-is:          Bench.hs
    build-depends:    base, time, math-parser
    default-language: Haskell2010

executable adversarial
    import:           warnings
    hs-source-dirs:   app
    main-is:          Adversarial.hs
    build-depends:    base, time, math-parser
    default-language: Haskell2010

test-suite test
    import:           warnings
    type:             exitcode-stdio-1.0
    hs-source-dirs:   app
    main-is:          Test.hs
    build-depends:    base, math-parser
    default-language: Haskell2010
