-- | Differential fuzz — every strategy must agree with every other.
--
-- Mirrors cpp/tests/fuzz_differential.cpp and python/test_fuzz.py: every one
-- of the 15 'allEvaluators' must produce the same value on a well-formed
-- expression (or all throw), and must draw the same accept/reject verdict on
-- a randomly mutated (usually malformed) one. This is what Haskell was
-- missing — the hand-written cases in Test.hs document the specification,
-- this enforces it in bulk, the same way the other three languages already
-- do. Two real bugs (empty-parens acceptance, a lexer bug) slipped past the
-- narrow spec suite and were only found by hand-probing; this closes that
-- gap.
--
-- Inputs come from bench/fuzz/{well_formed,mutated}.txt — the SAME files
-- every other language's fuzz test reads (generated by bench/gen_fuzz.py),
-- so a bug can't hide in one language's own untested corner. Variable
-- environment matches Test.hs and the other languages' fuzz tests: a=2,
-- b=3, c=4, d=5 (the shared generator only ever emits a/b/c/d as variables).
module Main (main) where

import Control.Exception (SomeException, evaluate, try)
import Control.Monad (unless)
import System.Directory (doesFileExist)
import System.Exit (exitFailure, exitSuccess)
import System.Process (callProcess)
import Text.Printf (printf)

import MathParser.Strategies

env :: Env
env i = case i of 0 -> 2; 1 -> 3; 2 -> 4; 3 -> 5; _ -> 0

nearly :: Double -> Double -> Bool
nearly a b
  | isNaN b   = isNaN a
  | a == b    = True            -- covers ±inf
  | otherwise = abs (a - b) <= 1e-9 * maximum [1, abs a, abs b]

fuzzDir :: String
fuzzDir = "../bench/fuzz"  -- relative to the haskell/ package root, matching
                           -- Bench.hs's "../bench/corpus" convention (cabal
                           -- test/run both use haskell/ as cwd)

wellFormedPath, mutatedPath :: String
wellFormedPath = fuzzDir ++ "/well_formed.txt"
mutatedPath = fuzzDir ++ "/mutated.txt"

-- Generates bench/fuzz/*.txt via bench/gen_fuzz.py if missing. Unlike the
-- C++/Rust shared-corpus checks (which skip gracefully if python3 isn't
-- available), this is Haskell's ONLY fuzz coverage, so a missing corpus
-- fails loudly with a clear fix rather than silently skipping the one real
-- check this test suite has.
ensureFuzzFiles :: IO ()
ensureFuzzFiles = do
  haveWf <- doesFileExist wellFormedPath
  haveMu <- doesFileExist mutatedPath
  unless (haveWf && haveMu) $ do
    putStrLn "shared fuzz corpus missing; generating via `python3 ../bench/gen_fuzz.py`"
    callProcess "python3" ["../bench/gen_fuzz.py"]
    haveWf' <- doesFileExist wellFormedPath
    haveMu' <- doesFileExist mutatedPath
    unless (haveWf' && haveMu') $
      ioError (userError
        "bench/fuzz/{well_formed,mutated}.txt still missing after running \
        \bench/gen_fuzz.py — run `python3 bench/gen_fuzz.py` from the repo \
        \root and retry")

-- splitlines-style: preserves blank lines (some mutated entries are
-- legitimately the empty string, a valid malformed-input case), and the
-- writer's sole trailing newline never becomes a spurious extra entry.
loadLines :: FilePath -> IO [String]
loadLines path = lines <$> readFile path

main :: IO ()
main = do
  ensureFuzzFiles
  wellFormed <- loadLines wellFormedPath
  mutated <- loadLines mutatedPath

  let evs = allEvaluators
  wfMismatches <- concat <$> mapM (checkAll evs) wellFormed
  muMismatches <- concat <$> mapM (checkAll evs) mutated
  let mismatches = wfMismatches ++ muMismatches

  mapM_ putStrLn mismatches
  printf "%d well-formed + %d mutated exprs x %d strategies (shared corpus), %d mismatch(es)\n"
         (length wellFormed) (length mutated) (length evs) (length mismatches)
  if null mismatches then exitSuccess else exitFailure

-- Evaluates every strategy on one expression; the first evaluator sets the
-- reference (value, or "threw"), every other must agree. Returns a printable
-- line per disagreement (empty list = all agreed).
checkAll :: [Evaluator] -> String -> IO [String]
checkAll [] _ = pure []
checkAll (ref : rest) expr = do
  (baseVal, baseThrew) <- tryEval ref expr
  results <- mapM (\ev -> do
                      (val, threw) <- tryEval ev expr
                      pure $ if threw /= baseThrew || (not threw && not (nearly val baseVal))
                             then Just (mismatchMsg ref expr baseVal baseThrew ev val threw)
                             else Nothing)
                   rest
  pure [msg | Just msg <- results]
  where
    tryEval :: Evaluator -> String -> IO (Double, Bool)
    tryEval ev e = do
      r <- try (evaluate (evRun ev env e)) :: IO (Either SomeException Double)
      pure $ case r of
        Right v -> (v, False)
        Left _  -> (0.0, True)
    mismatchMsg :: Evaluator -> String -> Double -> Bool -> Evaluator -> Double -> Bool -> String
    mismatchMsg r e bv bt other ov ot =
      printf "MISMATCH on %s: %s=%s vs %s=%s"
        (show e)
        (evName r) (if bt then "raise" else show bv)
        (evName other) (if ot then "raise" else show ov)
