#!/usr/bin/env python3
"""Differential fuzz — every strategy must agree with every other.

Mirrors cpp/tests/fuzz_differential.cpp: random well-formed expressions must
produce the same value from all fifteen strategies; randomly mutated (usually
malformed) ones must draw the same accept/reject verdict. Exit 0 on success,
1 on any mismatch.

This is what backs the "all strategies implement one specification" claim;
the hand-written cases in test_parsers.py document the specification, this
enforces it in bulk. The mutation stage matters: a pure well-formed generator
never produces adjacent operand groups like "(a)(b)", which is exactly the
input the shunting-yard family once silently accepted.

Inputs come from bench/fuzz/{well_formed,mutated}.txt — the SAME files every
other language's fuzz test reads (generated by bench/gen_fuzz.py, which
carries over this file's original generator/mutator and broadens it with
scientific-notation/overflow literals and tab/exponent-char mutations), so a
bug can't hide in one language's own narrower generator. Generated on demand
if missing.
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, __file__.rsplit("/", 1)[0])
from mathparser import all_evaluators  # noqa: E402
from test_parsers import VARS, nearly  # noqa: E402

FUZZ_DIR = os.path.join(ROOT, "bench", "fuzz")
WELL_FORMED_PATH = os.path.join(FUZZ_DIR, "well_formed.txt")
MUTATED_PATH = os.path.join(FUZZ_DIR, "mutated.txt")


def ensure_fuzz_files():
    if os.path.exists(WELL_FORMED_PATH) and os.path.exists(MUTATED_PATH):
        return
    subprocess.run([sys.executable, os.path.join(ROOT, "bench", "gen_fuzz.py")],
                    check=True)


def load_lines(path):
    # splitlines(), not "for line in f if line.strip()": some mutated lines
    # are legitimately the empty string (a valid malformed-input test case),
    # and splitlines() drops only the single trailing newline the writer
    # appends, not blank *entries*.
    with open(path) as f:
        return f.read().splitlines()


def main():
    ensure_fuzz_files()
    well_formed = load_lines(WELL_FORMED_PATH)
    mutated = load_lines(MUTATED_PATH)

    evs = all_evaluators()
    mismatches = 0

    def try_eval(ev, expr):
        try:
            return ev.eval(expr, VARS), False
        except Exception:  # noqa: BLE001 — any rejection counts the same
            return 0.0, True

    def check_all(expr):
        nonlocal mismatches
        base, base_raised = try_eval(evs[0], expr)
        for ev in evs[1:]:
            val, raised = try_eval(ev, expr)
            if raised != base_raised or (not raised and not nearly(val, base)):
                mismatches += 1
                print(f"MISMATCH on {expr!r}: {evs[0].name}="
                      f"{'raise' if base_raised else base!r} vs "
                      f"{ev.name}={'raise' if raised else val!r}")

    for expr in well_formed:
        check_all(expr)
    for expr in mutated:
        check_all(expr)

    print(f"{len(well_formed)} well-formed + {len(mutated)} mutated exprs "
          f"(shared corpus) x {len(evs)} strategies, {mismatches} mismatch(es)")
    return 0 if mismatches == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
